### ISSUE TITLE
running on Windows, running the step 5.5 cp -r .gitignore $(ls -1A | grep -v .git) ../cpapp, grep unknown command

### ISSUE THREAD

**Issue by islanderdev** [SAP-samples/cloud-cap-risk-management#13]

**Comment by smahati** [comment]
Hello,

On windows, grep is installed as part of the git installation. After installing git you can use the 'git bash' Command line interpreter. git bash includes utilities such as grep and it works only in git bash by default. We suggest that you use 'git bash' for this tutorial as described [here](https://developers.sap.com/tutorials/btp-app-set-up-local-development.html#70a28cd2-5cd4-41ee-a428-16e8a5274c49).

**Comment by iwonahahn** [comment]
Hi @islanderdev,

Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. If you still have questions, feel free to open a new issue.

Best regards,
Iwona
