### ISSUE TITLE
Annotations.cds file content mismatch when generated through VS code template wizard

### ISSUE THREAD

**Issue by SAP-Ayush** [SAP-samples/cloud-cap-risk-management#14]
When generating fiori application using template wizard the contents in the file cpapp/risks/annotations.cds are different than present in this repository. Mentioning this issue in the tutorial can be helpful.

**Comment by smahati** [comment]
Hi @SAP-Ayush,

Thank you for the heads up, there is a new option to add a table and object section in the generator. This can be set to `no` to avoid this issue in the future. The tutorial has been updated to reflect this change.

Best Regards,
Manjunath
