### ISSUE TITLE
Wrong entity in db/schema.cds

### ISSUE THREAD

**Issue by mnkv1988** [SAP-samples/cloud-cap-risk-management#16]
ext-service-add-consumption/db/schema.cds  is referring to a wrong entity where srv is referring to a different entity from external service. 

https://learning.sap.com/service/media/CLD200_20_en-US_media/CLD200_20_en-US_simulations/sap_wpb/trainer/9_5_3_371/trainer.html#mode=uebung&show=project!PR_AddanExternalService_Ex:uebung&hash=22

**Comment by markushaug** [comment]
Hi @mnkv1988, could you please specify exactly what you mean? As of now, it is not clear.

**Comment by smahati** [comment]
Hi @mnkv1988,

Closing this issue as there has been no reply. Please open another issue if you need support.

Best Regards,
Manjunath
