### ISSUE TITLE
CAP Application on Kyma - Use plain host instead of FQDN

### ISSUE THREAD

**Issue by gregorwolf** [SAP-samples/cloud-cap-risk-management#2]
Hi @d038359, Hi @uwe-klinger,

thank you for the great tutorial on how to [run a CAP Application on Kyma](https://sap-samples.github.io/cloud-cap-risk-management/Kyma). It inspired me to try it also with my [pg-beershop](https://github.com/gregorwolf/pg-beershop#run-on-sap-cloud-platform---kyma-environment) sample application. There I wanted to avoid as many manual steps as possible. So I've tried if I can avoid the FQDN in the host parameter of the APIRule. [And using](ttps://github.com/gregorwolf/pg-beershop/blob/master/deployment/beershop.yaml#L98):

```
spec:
  service:
    host: beershop
```

simply works. So I would suggest that you remove $CLUSTER_DOMAIN in the section [Prepare the Docker Registry](https://sap-samples.github.io/cloud-cap-risk-management/Kyma/#prepare-the-docker-registry).

Best regards
Gregor

**Comment by uwe-klinger** [comment]
Hi @gregorwolf,

Thanks for your hint. That makes it easier, indeed! :-) I've updated the tutorial.

Best regards
Uwe
