### ISSUE TITLE
Missing 'Create' option after generating 'List Report Object Page' using Fiori: Open Application Generator.

### ISSUE THREAD

**Issue by Nidhi-Sehgal** [SAP-samples/cloud-cap-risk-management#23]
![issue](https://user-images.githubusercontent.com/96954708/178939432-2d62ec17-aff1-4e40-8a19-993f77c729bc.png)

Is there any change in the steps to generate the UI?

**Comment by smahati** [comment]
@Nidhi-Sehgal ,

I tried it with the risk management service from our [tutorial](https://developers.sap.com/tutorials/btp-app-create-ui-fiori-elements.html), and it gets created with a create button. Can you try it with the service in our tutorial?

Best regards,
Manju

**Comment by Nidhi-Sehgal** [comment]
Hi Manju,

I tried generating the UI from both Business Application Studio as well as using VS Code locally. 
However, in both the cases, there is no create button in the generated UI. 

Is there a property that I need to set at the DB or SRV layer in the '.cds' files in CAP application that will trigger the appearance of a 'Create' button.

Thanks in advance for your response.

Regards,
Nidhi Sehgal

**Comment by smahati** [comment]
@Nidhi-Sehgal ,

In risk management this is done in the file `srv/risk-service.cds` where we enable drafts for the `Risks` entity using the annotation `@odata.draft.enabled`. You can read more about it in the CAP documentation [here](https://cap.cloud.sap/docs/advanced/fiori#enabling-draft-with-odatadraftenabled).

Best regards,
Manju

**Comment by Nidhi-Sehgal** [comment]
Hi @manjuX ,

Thanks for your response.

Does this imply that CAP applications will always be draft enabled?
Is there a possibility that I can have a CAP application in which I can create records without having draft mode?

If yes, then how can it be achieved?

Thanks.

Regards,
Nidhi Sehgal

**Comment by Nidhi-Sehgal** [comment]
Hi @manjuX 

Your response is awaited.

Regards,
Nidhi Sehgal

**Comment by smahati** [comment]
Hi @Nidhi-Sehgal,

This question falls outside the scope of our tutorial, please check the community support site for general questions regarding Fiori elements with the tag [SAP Fiori Elements](https://answers.sap.com/tags/ed5c1ef6-932f-4c19-b2ba-1be375109ff5).

Best Regards,
Manju
