### ISSUE TITLE
When navigate to Risk app and click go, the app warns "Unauthorized" instead of letting me to login

### ISSUE THREAD

**Issue by pjiang6** [SAP-samples/cloud-cap-risk-management#25]
In cap-roles, the "Sign in to access this site" dialog doesn't show. I've tried to allow the browser show pop-ups and notifications but still not working correctly.

**Comment by smahati** [comment]
Hi @pjiang6,

Did you add the users locally in the .cdsrc.json file as described?
If you did this can happen if you provided the wrong credentials once. To verify this you can try to access the page on a different browser.

If it works there you need to clear the credentials. You can clear your browser’s cache or simply close all browser windows to get rid of the login data in your browser. For Google Chrome, restart your browser (complete shutdown and restart) by entering chrome://restart in the address line.

Best regards,
Manju

**Comment by smahati** [comment]
Hi @pjiang6,

Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. If you still have questions, feel free to open a new issue.

Best regards,
Manju
