### ISSUE TITLE
Cf deploy

### ISSUE THREAD

**Issue by I501307** [SAP-samples/cloud-cap-risk-management#26]
app gets deployed to cf but not at all in working conditon : {"statusCode":401,"code":"401","message":"Unauthorized"}
can someone please share why am I getting this error? 

P.S : using this branch https://github.com/SAP-samples/cloud-cap-risk-management/tree/cap-mta-deployment

**Comment by smahati** [comment]
Hi @I501307,

Thank you for reaching out, that is the expected result as part of the tutorial [Deploy Your Multi-Target Application (MTA)](https://developers.sap.com/tutorials/btp-app-cap-mta-deployment.html#1eb1383c-3897-4b88-8a1e-b0005d7735f5), this is because it is part of a mission and the next parts take you through configuring the launchpad and the roles needed.

Hope this helps,
Best regards,
Manju

**Comment by I501307** [comment]
I have followed tutorial as you suggested and I still couldn't deploy to cf.

**Comment by I501307** [comment]
I have configured roles correctly following the documentation - but still I face **{"statusCode":401,"code":"401","message":"Unauthorized"}** - can you please assist me here?

**Comment by smahati** [comment]
Hi @I501307,

If you are getting the 404 error after you assigned the roles (which is done in this [tutorial](https://developers.sap.com/tutorials/btp-app-role-assignment.html)), you might have had your user already logged in and you need to logout before it takes the new roles. You can also take the link and open it in a different browser where you are not logged in already.

Best regards,
Manju

**Comment by I501307** [comment]
We have tried that already - this issue isn't related to cookies

**Comment by smahati** [comment]
Hi @I501307,

I started from the same branch you indicated and I was able to deploy the application and access the service on my trial account. Are you able to create and see the risks in the application? In case you are trying to access the risks directly it will not work as it needs authentication which is provided by accessing it through the UI in our tutorial. If you are not able to see the risks in the UI please share the link to your project, I can try to check if there is an issue.

Best regards,
Manju

**Comment by I501307** [comment]
Maybe we can take a look at this together if possible ? It is not working as shown in the tutorials.
For risks the url is : https://1b081f10trial.launchpad.cfapps.us10.hana.ondemand.com/a1cc8171-5d70-476c-923c-e131422ee6ee.cpappservice.nsrisks-1.0.0/index.html

**Comment by I501307** [comment]
![risk](https://user-images.githubusercontent.com/44555906/206218378-a3e15e9d-5fb8-4f95-8b40-372e0c78ffc9.PNG)

**Comment by smahati** [comment]
Hi @I501307,

As discussed, please create your DB instance as described in our mission and redeploy your application. To see the changes updated you would need to reconfigure the launchpad. If you face problems related to our tutorial please create a new issue.

Best regards,
Manju

**Comment by I501307** [comment]
Thank you for the effort and time here 👍
