### ISSUE TITLE
How to navigate SAP S/4 HANA Cloud tenant launchpad in trial account

### ISSUE THREAD

**Issue by merveguel** [SAP-samples/cloud-cap-risk-management#28]
Hello all,

Could you please share from where exactly we can find this below launchpad page in a **trial** account, where should we navigate?

https://developers.sap.com/tutorials/btp-app-ext-service-s4hc-register.html
Step 2 : Add integration token to SAP S/4HANA Cloud system
![image](https://user-images.githubusercontent.com/14961341/216759079-d17fa162-5785-40cd-a1f1-1480ebf3fdda.png)

Thanks in advance,
Merve

**Comment by smahati** [comment]
Hi @merveguel ,

For this part of tutorial you need a S/4 Hana License and system access as mentioned in the pre-requisites: 

```

- You have a dedicated SAP S/4HANA Cloud tenant
- You must be an administrator of the SAP S/4HANA Cloud system
- You need to connect this system to your SAP BTP global account, if you’d like to build extension applications for your SAP S/4HANA Cloud system

```
You can see that a mission needs a Licensed system by this icon shown:
![screenshot highlighting the lock icon on the preview card of the mission](https://user-images.githubusercontent.com/93712176/216924718-cd4ad8b9-6534-4774-b0db-551c907b92a3.png)

Best regards,
Manju

**Comment by smahati** [comment]
Hi @merveguel ,

As it has been 3 weeks without a response I am closing this issue. Please open a new issue in case you need support with our tutorials.

Best regards,
Manju
