### ISSUE TITLE
Docker build fails due to missing python

### ISSUE THREAD

**Issue by tobiashofmann** [SAP-samples/cloud-cap-risk-management#3]
Following the tutorial, when I get to build the Docker container for the first time (docker build -t cpapp .) the step fails.

**Error**

When the run npm step of the Dockerfile is reached, the installation of sqlite3 fails. No pre-compiled version is available, therefore npm tries to build one. This fails as no python is installed. Python is not part of the used node:12-slim image.

> sqlite3@5.0.1 install /usr/src/app/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.1 and node@12.20.1 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
...
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:

**Solution**

When python is available, the image is build successfully. Changing the Dockerfile to use a node image that includes python makes the build work. 

FROM node:12

As an alternative, add python by installing it in the Dockerfile.

**Comment by uwe-klinger** [comment]
Hi @tobiashofmann,

Sorry, for the late reply and thanks for pointing that out. It looks like the prebuild version is available for current sqlite 5.0.2, so the problem doesn't occur right now. But it can come back...

We will add a note to the tutorial about this problem. We've chosen node12-slim to reduce the size of the docker image. Another approach would be to have a separate docker build step, but that's too complicated for this starter tutorial.

Thanks & Best regards,
Uwe
