### ISSUE TITLE
The deployment of application is failing for the pipeline risks-analytics

### ISSUE THREAD

**Issue by Askullu** [SAP-samples/cloud-cap-risk-management#35]
Hi,

The staging of the application cpapp-srv is failing as the node 16 can't be found in the buildpack of branch 'launchpad-service' of [repo](https://github.com/SAP-samples/cloud-cap-risk-management.git) in package.json file. Below is the error logs:
![image](https://github.com/SAP-samples/cloud-cap-risk-management/assets/75372983/2d317f86-8eb5-4c84-a3ae-8659f0094928)

Also, could you please update the cds version to the latest one? As of now, it is running in version 6.

Thanks & Regards,
Akanksha

**Comment by C5324260** [comment]
Hi @uwe-klinger 
We are blocked due to the lower version of node and the automation test suit is failing and running the automation suit is high priority to my team so please have a look at the ticket

Regards,
Vinay C

**Comment by smahati** [comment]
Hello,
Do you take the code from this repository to be used in the automation test?
Best regards,
Maha

**Comment by C5324260** [comment]
Hi Maha,
Yes we use this repo for automation

Regards,
Vinay C

**Comment by smahati** [comment]
Also @C5324260 , which branches do you need? we plan to delete some branches.

**Comment by C5324260** [comment]
"launchpad-service" and "analytics" is the required branch

**Comment by C5324260** [comment]
Hi @smahati  Any updates as we are blocked

**Comment by smahati** [comment]
Hi @C5324260 ,

I'll push the update today, there is a pipeline and sometimes it causes a bit of delay but I'll keep you updated.

Best regards,
Maha

**Comment by smahati** [comment]
I've made the update, I don't see the change yet but the builds are triggered and passing. Hopefully we can see it soon.

Best regards,
Maha

**Comment by smahati** [comment]
Hello,
The changes are visible now, please let me know if this works now.
Best regards,
Maha

**Comment by C5324260** [comment]
Hi 
Yes, it is working fine now

Regards,
Vinay C

**Comment by smahati** [comment]
Thanks for confirming. I'll close this issue.

Best regards,
Maha
