### ISSUE TITLE
cds run call is deprecated and has to be replaced by cds-serve

### ISSUE THREAD

**Issue by C5324260** [SAP-samples/cloud-cap-risk-management#36]
Hi Team
We are from last Mile Testing Team
We run the Risk analytics automation test suit where we use your repository 
https://github.com/SAP-samples/cloud-cap-risk-management/tree/launchpad-service
https://github.com/SAP-samples/cloud-cap-risk-management/tree/analytics

We are facing a different issue now when deployment of application is getting failed with CDS not found error.
As in package.json =  "start": "cds run", command is deprecated in latest version of CDS so we need to change to 
 "scripts": {
        "start": "cds-serve",

https://cap.cloud.sap/docs/node.js/cds-server#cli-command-cds-serve

Please have a look and change the required one 

Regards,
Vinay C

**Comment by smahati** [comment]
Hi Vinay,

I'll make the change.

Thanks for reporting!

**Comment by smahati** [comment]
Done.
best regards,
Maha

**Comment by smahati** [comment]
closing as this was done.
