### ISSUE TITLE
Implement Roles and Authorization Checks In CAP : File not available in the shared location templates/cap/roles/.cdsrc.json

### ISSUE THREAD

**Issue by ibibhu** [SAP-samples/cloud-cap-risk-management#5]
https://developers.sap.com/tutorials/btp-app-cap-roles.html >
Step 3: Add Users for Local Testing : 

"Copy the file templates/cap/roles/.cdsrc.json to your project directory cpapp"

The following file is not present in the template/roles directory of the tutorial

templates/cap/roles/.cdsrc.json 

![image](https://user-images.githubusercontent.com/5914863/123173524-5cb0a800-d49c-11eb-8e9c-6b351129336e.png)

**Comment by ibibhu** [comment]
I have added the below and It worked for me

`{
  "requires": {
    "[development]": {
      "auth": {
        "strategy": "mock",
        "users": {
          "risk.viewer@tester.sap.com": {
            "password": "initial",
            "ID": "risk.viewer@tester.sap.com",
            "userAttributes": {
              "email": "risk.viewer@tester.sap.com"
            },
            "roles": [
              "RiskViewer"
            ]
          },
          "risk.manager@tester.sap.com": {
            "password": "initial",
            "ID": "risk.manager@tester.sap.com",
            "userAttributes": {
              "email": "risk.manager@tester.sap.com"
            },
            "roles": [
              "RiskManager"
            ]
          }
        }
      }
    }
  }
}`

**Comment by uwe-klinger** [comment]
Hi @ibibhu ,

Thanks a lot for reporting this issue.

The file is now available: https://github.com/SAP-samples/cloud-cap-risk-management/blob/master/templates/cap/roles/.cdsrc.json

The content that you used looks good.

Best regards,
Uwe
