### ISSUE TITLE
Adding MTA via cds add mta does not work

### ISSUE THREAD

**Issue by d066471** [SAP-samples/cloud-cap-risk-management#7]
Hi,

Adding an MTA file in your root CAP application does not work via command **cds add mta**. It fails with following error:

`[cds] - adding feature(s) to project in current folder
[cds] > adding feature 'mta'...
[ERROR] Build task could not be resolved - module [./hana] cannot be loaded:
TypeError: cds.utils.promisify is not a function`

"@sap/cds": "^5" is being used.

Best regards,
Brijesh

**Comment by d066471** [comment]
Well with upgrading to @sap/cds-dk: 4.3.1, this issue does not happen.

**Comment by uwe-klinger** [comment]
Hi Brijesh,

I'm closing this issue, as it seems to be an already solved bug.

Best regards,
Uwe
