### ISSUE TITLE
mbt build fails

### ISSUE THREAD

**Issue by d066471** [SAP-samples/cloud-cap-risk-management#8]
Hi,

For the mitigation app, the @ui5/cli version is outdated in package.json and hence the build is failing.
I think it has to be updated to 2.11.1 too like the risks app as the specVersion 2.4 in ui5-deploy.yaml does not resonates well with the ui5-cli version. See here: https://sap.github.io/ui5-tooling/pages/Configuration/#specification-versions 

After updating the ui5 cli version, the build is passing. 

Best regards,
Brijesh

**Comment by uwe-klinger** [comment]
Hi Brijesh,

Thanks for raising this issue.

We have updated the tutorial to explain the required version change.

Best regards,
Uwe
